### PR TITLE
Add EULA tests

### PR DESCRIPTION
**Pull request by ravolt**
I added the path and forgot to add the tests.
Here they are.

### CODE REVIEW

**Comment by galthaus** [comment]
This doesn't look correct.  It seems like you started from the incorrect tree.

**Comment by zehicle** [comment]
Yikes!  Omg -1!!!

**Comment by ravolt** [comment]
replaced with correct one

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6cz9me-in&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=b8SGW6Wo&invitationId=6118771197770555392








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6cz9me-in&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGXuK-d16bbkwAAAVOo-HNxO0VxqHrm_zju5BrTjxuK5BLcU96ZueDqFCahbq_D_OxVpp7O6Tgq4N19-hwLjNFOAdS4UnslIOfk9iastdXaTfCZ2iaPb3GJhwR0oYJkkFRHdTG-A2odT-bKoPgYfm_QzHMwN2YshSifoKlSBnSIO1CQU55hfoTsgX7B2SycZe2M&eid=0-im6cz9me-in


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6cz9me-in&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=7x0gxq-imfatzo6-ku&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=b8SGW6Wo&invitationID=6118771197770555392

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=7x0gxq-imfatzo6-ku&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=b8SGW6Wo&invitationID=6118771197770555392





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=7x0gxq-imfatzo6-ku&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=7x0gxq-imfatzo6-ku&loid=AQH-48zphbWk4QAAAVPJ-M-Q67iFMM1lnKe4Rdru_1Cjm6XzwfIV0pp8_yHgqhq1nxF3q8s7UIcHOC_vLvM56vlxp6cFf10ZiPYFSik1pxM9K5TWk3wL9m9eWc0C-JYN6JdLVavhCznczXoW0sq_9ilCqjoSePSkXETVEJBNIvd3piAxD79RDa16DUp1K9nxmFDY

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=7x0gxq-imfatzo6-ku&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=7x0gxq-impb4wx0-r4&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=b8SGW6Wo&invitationID=6118771197770555392

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=7x0gxq-impb4wx0-r4&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=b8SGW6Wo&invitationID=6118771197770555392





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=7x0gxq-impb4wx0-r4&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=7x0gxq-impb4wx0-r4&loid=AQFZuBv4sIQCkwAAAVPuBMPPmF1csIQPKrQxVqTNnbFgYWPEiG1XwrnLL_OTugA-v6b72i8L1RTTkxDhZh7bzntGHsUHMlGJYEjCbrcTSKmCeG1-4JqWr0dh1b0JTfUHHeXKlkSam72FaIh5sxCQgELzXYP3_4RhmyB28DEcqk_Nq6TfoBLnqHNxbQV2XrhY24tP

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=7x0gxq-impb4wx0-r4&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
