### PR TITLE
refactor docker-admin for #372

### PR DESCRIPTION
**Pull request by dudymas**
This refactor addresses #372

This PR has two commits with the following respective ideas:

1. first, reorganize the existing docker-admin script to make it easier for multiple developers to work on it.
  - if someone is working on a new function (ie. containerizing the db) they can easily add to docker-admin
  - if there is a bug with an existing function, the developer is isolated to just treating docker-admin-functions
2. design docker-admin to cleanly start/rejoin existing containers rather than clobber them and die

### CODE REVIEW

**Comment by dudymas** [comment]
I went ahead and merged with opencrowbar/core and found a few files out of date. The PR isn't using them, but apparently Travis is still checking out older code... ?

**Comment by dudymas** [comment]
I updated commit b4ae5c9

The docker-admin was not always running commands in the shell.

If you want me to clean up the other commits in my attempt to remove the Travis build errors, let me know. I was told that all these commits won't fix the Travis Builder, but I'm keeping them for now... might as well...

**Comment by VictorLowther** [comment]
This needs to be rebased against the current develop -- it pulls in duplicates of several things that are already there.

**Comment by VictorLowther** [comment]
I will do a more complete review once this PR is rebased and non-standalone commits squashed.

**Comment by dudymas** [comment]
I reworked the commits to make this easier to revise

I also edited the final commit to reflect some changes that @VictorLowther recommended

**Comment by dudymas** [comment]
ooo, the CLAHub thing is pretty neat.

**Comment by dudymas** [comment]
Thanks for cleaning this up. I hope at some point I'll have time to revisit.

**Pull request closed without merging**
