### PR TITLE
Its Hammer Time!  BDD coverage for power changes

### PR DESCRIPTION
**Pull request by ravolt**
I added tests to ensure that we test Hammer power changes via API and CLI
Since I got the BDD CLI tests working again, I also added those tests back.

I made it so the power fails return better massages and a 501 error instead of 500.
I also had to make it work for dev mode with a simple catch

I refactored how we return "results" and made BDD able to handle it

connect to #430

### CODE REVIEW

**Comment by ravolt** [comment]
Added CLI command to reset passwords.  Connect to #472 
This should address issue raised by @dudymas 

NOTE: There are still several other user commands missing (lock, admin)

**Comment by galthaus** [comment]
BDD Cli test failed.  Didn't look too closely as to why.

**Comment by cloudedge** [comment]
fixed

On 02/21/2015 11:29 PM, Greg Althaus wrote:
>
> BDD Cli test failed. Didn't look too closely as to why.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/opencrowbar/core/pull/478#issuecomment-75420759>.
>

-- 
   

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6czhek-xo&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=NjxIrFDz&invitationId=6118771170629206016








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6czhek-xo&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH0cjiylNGcwAAAAVOo-JvQmFzESx0h0AiAkcVW3bwWb6Dr3Xmg8URGbZO07jZVNSYg9KkB7aduF0BNeAZWUus_HrCZEvh5jowId6YZVq4dGMiCxxQHHOHNyfnkDCz4CBUkAnAE_dfs0ituoRKkqtqutYPUPfz5FlEpS_Mb5VcDC_OvCPogmdu3sywuTidvxXm8&eid=0-im6czhek-xo


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6czhek-xo&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=frzi6j-imfau6h8-lt&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=NjxIrFDz&invitationID=6118771170629206016

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=frzi6j-imfau6h8-lt&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=NjxIrFDz&invitationID=6118771170629206016





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=frzi6j-imfau6h8-lt&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=frzi6j-imfau6h8-lt&loid=AQHgbezx-Hp34gAAAVPJ-IL7UEL1vTmZYyCZG-u5i21Kw1TTcY3Urhmx0KqL-iVEMDUwlu5SQwh0d5SZZb4avUHtPZVb21Ahqepj-hdOW4OkgVI6FSuSN-KbZRQihm9g1PP3XisVINcbuf6U6JGsGPk8pAs9V1tuWnkbkFdpbYnNTYgDimz0TSnGp7bC-EemSq3V

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=frzi6j-imfau6h8-lt&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
