### PR TITLE
Make the crowbar-access role noop (as it should be)

### PR DESCRIPTION
**Pull request by galthaus**

### CODE REVIEW

**Comment by VictorLowther** [comment]
In my version of this I also bound it to the admin node instead of the system phantom node.  That lets it participate in the graph without it deadlocking against the consul cutout noderoles

**Comment by galthaus** [comment]
Okay sounds good I'll add it that too.

**Comment by sjensen** [comment]
This role seems to be part of the script jig not the noop jig.  Can you please confirm?

**Comment by galthaus** [comment]
This has been moved and moved around again.  it is not a script role on individual nodes to setup access.  This used to be a single data holding role on the system phantom node.  It now does more and lives elsewhere.

**Pull request merged**
