### PR TITLE
Zap no longer fake enough admin name

### PR DESCRIPTION
**Pull request by VictorLowther**

### CODE REVIEW

**Comment by galthaus** [comment]
Hit this once on making my own admin name.  Very disturbing.

**Comment by sjensen** [comment]
what does this mean?

**Comment by galthaus** [comment]
The kvm admin node picks a name for the admin node to speed up bring-up.  There is a list of names that aren't real in the internets. It turns out that the one deleted is real.  If you end up using a resolvable name, it wigs out the system (if it doesn't match the address we have).  The pull request is to remove the "real" name from the internet.

**Comment by sjensen** [comment]
great.  Adding a new label to track Dev Env only issues

**Pull request merged**
