### PR TITLE
Camshaft Ver

### PR DESCRIPTION
**Pull request by ravolt**
add digest auth path to API

### CODE REVIEW

**Comment by galthaus** [comment]
What are you trying to do?  This does not merge correctly.

**Comment by zehicle** [comment]
I wanted to make sure that this URL is available for the last release

On Fri, May 1, 2015 at 10:01 AM, Greg Althaus <notifications@github.com>
wrote:

> What are you trying to do? This does not merge correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencrowbar/core/pull/563#issuecomment-98149523>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by galthaus** [comment]
So, you are trying to add a new feature to a closed release?
I assume that you are going to say yes.

You will need to cherry-pick them onto master and submit that as a pull request.
Then we will need to run tests, update minor numbers, build RPMs, cut new tags, and publish a new release.

**Comment by zehicle** [comment]
ok, I'll start that when the time comes
I would NOT respin the release at this time.

On Fri, May 1, 2015 at 10:08 AM, Greg Althaus <notifications@github.com>
wrote:

> So, you are trying to add a new feature to a closed release?
> I assume that you are going to say yes.
>
> You will need to cherry-pick them onto master and submit that as a pull
> request.
> Then we will need to run tests, update minor numbers, build RPMs, cut new
> tags, and publish a new release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencrowbar/core/pull/563#issuecomment-98151462>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6czc90-qb&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=4Tn2V5js&invitationId=6118771169471578114








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6czc90-qb&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFtysJHTG35PwAAAVOo-G9yrdrMv_LRqG5KeSgeo8EpsT6YjJ9mpSuQ8i9tJKO-QUDsHoAr0W0Xzy2pNVbBbfZaz6RkUxoauiQCNgdYBvy8bco8HCwWSoSXmcUn-K4J2U64xtL-zlUWk1SW2HXKu_e19LRCfgbuGzmWAyJRxluopbHNLqTj3yIDBReUvg9e7_1a&eid=0-im6czc90-qb


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6czc90-qb&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6czfwb-il&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Ua3ml6lj&invitationId=6118771169186377728








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6czfwb-il&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEQgbymuCjTJgAAAVOo-JLdyz6kjWN6k298TsTmGdSMUTySPv7rh3ETS_D2A0TeTGCqY9p2Wkaz-o9DJzJywnUfGCuOnLse9dqIOU_OpVuVSGjAdnX2w0mgRwL6lSq4MP0rM-qmMaRvNWeEoXrpH0QiOOpNlRfPRC9n3OczboEgTKwhakI4ZB05jNjg5YhRxiET&eid=0-im6czfwb-il


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6czfwb-il&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=wyhajf-imfatvka-4b&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=Ua3ml6lj&invitationID=6118771169186377728

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=wyhajf-imfatvka-4b&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Ua3ml6lj&invitationID=6118771169186377728





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=wyhajf-imfatvka-4b&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=wyhajf-imfatvka-4b&loid=AQHXtgriAdZu3AAAAVPJ-EFcfZ8fheGzUL4CGZ3QlyPjMmZPbEvPTwcpUMywb81eLLzPmXGj36b-uO6gE7EQliLCUcqCionrIGPKBHJdugmMpS3FYf_NtdL8c9Rxi3MDLIk2YsTYjAZFZ8i1J0Uo80vkVYO21vm-329uHcXICEkhhxw-ELYXEQbLUujSzgS2UhcD

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=wyhajf-imfatvka-4b&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-pxhype-imfau6h9-z3&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=4Tn2V5js&invitationID=6118771169471578114

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-pxhype-imfau6h9-z3&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=4Tn2V5js&invitationID=6118771169471578114





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-pxhype-imfau6h9-z3&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-pxhype-imfau6h9-z3&loid=AQGCr2Pr_f1XggAAAVPJ-EXEDxRfoogI0-1ZFg6klKjKUgRyDf7O9gxEnH8wMI53I-5N80Td7Kmhb68MsA2-_DLcqWOwUSN27kfdbR61sXZjuu4OP_a6sGrTipHr289ueFihnBSNTDnnz-5WFoBge4Ie093nBNLgVTffYeVYHQ5f0UKYZSL4wKiXhH8F-U_NNILk

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-pxhype-imfau6h9-z3&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-pxhype-impb4ww3-2&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=4Tn2V5js&invitationID=6118771169471578114

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-pxhype-impb4ww3-2&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=4Tn2V5js&invitationID=6118771169471578114





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-pxhype-impb4ww3-2&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-pxhype-impb4ww3-2&loid=AQHSTcywktn0ZgAAAVPuBMczzUt7iWC45hOFQAyDE6QbOOzah3cc3x8DCaRKkx6m1BQ_OixWwfbY5cIsxsfPbfX5gAEkWfONu53PgGbJntNAK7XoILgNkW3eJ_u_GO8wVO5Dk0WB98s6tzUGvntaK0dN4OYkoX73hSNGz0lkhH58U7NKgulHRXbjguwvAO7yyR7l

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-pxhype-impb4ww3-2&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=wyhajf-impb4u2r-kc&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=Ua3ml6lj&invitationID=6118771169186377728

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=wyhajf-impb4u2r-kc&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Ua3ml6lj&invitationID=6118771169186377728





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=wyhajf-impb4u2r-kc&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=wyhajf-impb4u2r-kc&loid=AQHpnPX7IbjnagAAAVPuBNCz0bm8q_OuCm915vy7QD_dhCPp9YOIIwBhK84sewP2YJzz0ggBwo7EgbvVDkmwZVqA_KlgUs9eaM_VkrQL6f56i_6Z0UM_SYaAfwz7IENqzuO8Aolxf-Rk0rJIPJ0n5ju86jVEiMgPWgDW05KFzPUbnWpBRGLgvLzXgiaE90rPS3AT

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=wyhajf-impb4u2r-kc&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
